AVAILABLE_TOOLS = """
You have access to the following tools to interact with Livspace's internal systems. You must use these tools whenever the script indicates that information is needed or an action must be taken.

get_project_details(identifier: str, identifier_type: str)
Description: Retrieves details for an existing customer's project using either their Project ID or registered mobile number.
Parameters:
    - identifier: The Project ID (e.g., "BLR12345") or phone number (e.g., "9876543210").
    - identifier_type: Must be either 'project_id' or 'phone_number'.
Returns: A JSON object with project status, assigned team members, and customer details, or null if not found.

check_serviceability(pincode: str)
Description: Checks if Livspace provides services for a given pin code.
Parameters: 
    - pincode: The 6-digit pin code (e.g., "560033").
Returns: {'serviceable': true, 'city': 'Bangalore'} or {'serviceable': false}.

get_minimum_budget(city: str, project_type: str)
Description: Fetches the minimum budget requirement for a specific city and project type.
Parameters:
    - city: The city name (e.g., "Chandigarh").
    - project_type: Must be either 'new_build' or 'renovation'.
Returns: A JSON object with the minimum budget (e.g., {'min_budget': 200000}).

create_lead_ticket(name: str, phone: str, email: str, city: str, pincode: str, project_type: str, scope_summary: str, budget: int)
Description: Creates a new lead ticket in the CRM for a qualified potential customer.
Parameters: All customer details gathered during the qualification phase.
Returns: A confirmation with a new lead ID (e.g., {'status': 'success', 'lead_id': 'LID54321'}).

schedule_appointment(lead_id: str, appointment_type: str, datetime: str, notes: str)
Description: Schedules an appointment (briefing call or site visit) for a new lead.
Parameters:
    - lead_id: The ID generated by create_lead_ticket.
    - appointment_type: Must be 'briefing_call' or 'site_visit'.
    - datetime: The scheduled date and time in ISO format.
    - notes: Any relevant notes for the designer.
Returns: A confirmation message.

create_support_ticket(project_id: str, issue_category: str, summary: str, callback_requested: bool, preferred_time: str)
Description: Creates a standard support ticket for an existing project query.
Parameters:
    - project_id: The customer's project ID.
    - issue_category: e.g., 'Status Update', 'Payment Query', 'Delay Concern'.
    - summary: A brief description of the customer's issue.
Returns: A confirmation with a new ticket ID.

create_escalation_ticket(project_id: str, summary: str, customer_sentiment: str)
Description: Creates a high-priority escalation ticket for a serious customer complaint.
Parameters:
    - project_id: The customer's project ID.
    - summary: A detailed summary of the customer's complaint and demands.
    - customer_sentiment: e.g., 'Angry', 'Frustrated', 'Threatening Social Media'.
Returns: A confirmation with a high-priority ticket ID.

update_contact_preferences(phone: str, action: str)
Description: Updates a user's contact preferences in the system.
Parameters:
    - phone: The customer's phone number.
    - action: Must be 'unsubscribe' or 'delete_data'.
Returns: A confirmation message.
"""